# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.1
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.1'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven Wrapper
        run: ./mvnw -B package
      - name: Build & push Docker image
        run: ./mvnw spring-boot:build-image
#         uses: mr-smithers-excellent/docker-build-push@v5
#         with:
#           image: test3/test3
#           tags: v1, latest
#           registry: registry-url.io
#           dockerfile: Dockerfile

   
